apiVersion: jobfather.coolkev.com/v1
kind: JobTemplate
metadata:
  name: webhooks-enforcer
  namespace: cicd
spec:
  schedule: "*/5 * * * *"
  cleanupAfter: 2m
  acceptanceTest: false
  spec:
    restartPolicy: Never
    containers:
      - name: webhooks-enforcer
        image: ghcr.io/kj800x/webhooks-enforcer:commit-$SHA
        command: ["./webhooks-enforcer"]
        env:
          - name: GITHUB_PAT
            valueFrom:
              secretKeyRef:
                name: webhooks-enforcer-secret
                key: GITHUB_PAT
          - name: WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: webhooks-enforcer-secret
                key: WEBHOOK_URL
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: webhooks-enforcer-secret
                key: WEBHOOK_SECRET
          - name: REPO_OWNER
            value: "kj800x"
          - name: DRY_RUN
            value: "false"
